version: '3.8'

services:
  bot:
    build: .
    container_name: web
    command: ./main_bot.py
    depends_on:
      db:
        condition: service_started

    restart: always


    env_file:
      - .env
  db:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      -  postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

volumes:
  postgres_data: